start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_PurchaseLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_PurchaseLines2.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_SalesLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_Items.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_Locations.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_SalesOrderHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_Customers.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_Salespeople.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_ValueEntries.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_PostedSalesInvoiceHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_PostedSalesInvoiceLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_PostedSalesCreditMemoHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\TRS\TRS_PostedSalesCreditMemoLines.bat
