start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_PurchaseLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_PurchaseLines2.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_SalesLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_Items.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_Locations.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_SalesOrderHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_Customers.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_Salespeople.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_ValueEntries.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_PostedSalesInvoiceHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_PostedSalesInvoiceLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_PostedSalesCreditMemoHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\FLR\FLR_PostedSalesCreditMemoLines.bat
