start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_PurchaseLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_PurchaseLines2.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_SalesLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_Items.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_Locations.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_SalesOrderHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_Customers.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_Salespeople.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_ValueEntries.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_PostedSalesInvoiceHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_PostedSalesInvoiceLines.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_PostedSalesCreditMemoHeaders.bat
start C:\Users\eviadmin\Documents\Datawarehouse\schedule_scripts\From_BC\batches\CTL\CTL_PostedSalesCreditMemoLines.bat
